# Generated by Django 6.0.1 on 2026-01-31 13:30

import django.db.models.deletion
import domain.school_operations.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('name', models.CharField(help_text="Nom complet de l'école (ex: Lycée Filima)", max_length=200, verbose_name='nom')),
                ('code', models.CharField(help_text="Code unique de l'école (ex: LYC-FILIMA-001)", max_length=50, unique=True, validators=[domain.school_operations.validators.validate_school_code], verbose_name='code')),
                ('school_type', models.CharField(choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('technique', 'Technique/Professionnel'), ('superieur', 'Supérieur'), ('formation_prof', 'Formation Professionnelle')], help_text="Type d'établissement scolaire", max_length=20, verbose_name="type d'école")),
                ('ownership', models.CharField(choices=[('public', 'Public'), ('private', 'Privé'), ('community', 'Communautaire'), ('religious', 'Religieux'), ('ngo', 'ONG')], default='public', help_text="Type de propriété de l'école", max_length=20, verbose_name='statut')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('closed', 'Fermé')], db_index=True, default='draft', help_text="État opérationnel de l'école", max_length=20, verbose_name='état')),
                ('address', models.TextField(blank=True, help_text="Adresse détaillée de l'école", verbose_name='adresse')),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone (format Guinée)', max_length=20, validators=[domain.school_operations.validators.validate_guinea_phone], verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, help_text='Adresse email de contact', max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, help_text="Site web de l'école (optionnel)", verbose_name='site web')),
                ('capacity', models.PositiveIntegerField(blank=True, db_index=True, help_text="Capacité maximale d'élèves", null=True, verbose_name='capacité')),
                ('settings', models.JSONField(blank=True, default=dict, help_text="Configuration spécifique à l'école (JSON)", validators=[domain.school_operations.validators.validate_school_settings], verbose_name='paramètres')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('director', models.ForeignKey(blank=True, help_text="Directeur de l'école (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_schools', to=settings.AUTH_USER_MODEL, verbose_name='directeur')),
                ('locality', models.ForeignKey(help_text="Localité où se situe l'école", on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='geography.locality', verbose_name='localité')),
                ('registrar', models.ForeignKey(blank=True, help_text='Responsable administratif (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_schools', to=settings.AUTH_USER_MODEL, verbose_name='registraire')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'école',
                'verbose_name_plural': 'écoles',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='school_code_idx'), models.Index(fields=['status'], name='school_status_idx'), models.Index(fields=['school_type'], name='school_type_idx'), models.Index(fields=['locality'], name='school_locality_idx'), models.Index(fields=['locality', 'status'], name='school_locality_status_idx'), models.Index(fields=['capacity'], name='school_capacity_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='positive_capacity')],
            },
        ),
    ]
