# Generated by Django 6.0.1 on 2026-01-31 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_academicyear_unique_academic_year_period_and_more'),
        ('school_operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('name', models.CharField(help_text='Nom lisible (ex: Lycée Filima 2024-2025)', max_length=200, verbose_name='nom')),
                ('code', models.CharField(blank=True, help_text='Code court auto-généré (ex: LYC-FILIMA-001-2024-2025)', max_length=50, verbose_name='code')),
                ('start_date', models.DateField(help_text="Date de début de l'année scolaire (typiquement en octobre en Guinée)", verbose_name='date de début')),
                ('end_date', models.DateField(help_text="Date de fin de l'année scolaire (typiquement en juin)", verbose_name='date de fin')),
                ('enrollment_start_date', models.DateField(blank=True, help_text="Date de début de la période d'inscription", null=True, verbose_name='début des inscriptions')),
                ('enrollment_end_date', models.DateField(blank=True, help_text="Date de fin de la période d'inscription", null=True, verbose_name='fin des inscriptions')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text="Capacité totale pour cette année scolaire (ne peut pas dépasser la capacité de l'école)", null=True, verbose_name='capacité')),
                ('current_enrollment_count', models.PositiveIntegerField(default=0, help_text="Nombre d'élèves actuellement inscrits (mis à jour automatiquement)", verbose_name="nombre d'inscriptions actuelles")),
                ('status', models.CharField(choices=[('planning', 'Planification'), ('active', 'Actif'), ('completed', 'Terminé'), ('archived', 'Archivé')], db_index=True, default='planning', help_text="Statut de l'année scolaire", max_length=20, verbose_name='statut')),
                ('is_current', models.BooleanField(default=False, help_text="Indique si c'est l'année scolaire actuelle pour cette école", verbose_name='année en cours')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Configuration spécifique à cette année scolaire (périodes, vacances, règles)', verbose_name='paramètres')),
                ('description', models.TextField(blank=True, help_text='Description ou notes pour cette année scolaire', verbose_name='description')),
                ('academic_year', models.ForeignKey(help_text="Référence d'année académique globale", on_delete=django.db.models.deletion.PROTECT, related_name='school_years', to='academic.academicyear', verbose_name='année académique')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school', models.ForeignKey(help_text='École associée à cette année scolaire', on_delete=django.db.models.deletion.PROTECT, related_name='school_years', to='school_operations.school', verbose_name='école')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Année Scolaire',
                'verbose_name_plural': 'Années Scolaires',
                'db_table': 'school_year',
                'ordering': ['-start_date', 'school__name'],
                'indexes': [models.Index(fields=['school', 'status'], name='school_year_school_status_idx'), models.Index(fields=['school', 'is_current'], name='school_year_school_current_idx'), models.Index(fields=['academic_year'], name='school_year_academic_year_idx'), models.Index(fields=['status'], name='school_year_status_idx'), models.Index(fields=['start_date', 'end_date'], name='school_year_period_idx'), models.Index(fields=['school', 'start_date'], name='school_year_school_start_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school', 'academic_year'), name='unique_school_academic_year'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school', 'name'), name='unique_school_year_name'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school', 'start_date', 'end_date'), name='unique_school_year_dates'), models.UniqueConstraint(condition=models.Q(('is_current', True), ('is_deleted', False)), fields=('school',), name='unique_current_school_year'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'active')), fields=('school',), name='unique_active_school_year'), models.CheckConstraint(condition=models.Q(('capacity__gt', 0), ('capacity__isnull', True), _connector='OR'), name='school_year_positive_capacity'), models.CheckConstraint(condition=models.Q(('current_enrollment_count__gte', 0)), name='school_year_non_negative_enrollment')],
            },
        ),
    ]
