# Generated by Django 6.0.1 on 2026-01-31 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_academicyear_unique_academic_year_period_and_more'),
        ('school_operations', '0002_schoolyear'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYearCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('cycle', models.ForeignKey(help_text='Cycle enseigné (référence master)', on_delete=django.db.models.deletion.PROTECT, related_name='school_year_cycles', to='academic.cycle')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year', models.ForeignKey(help_text='Année scolaire associée', on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='school_operations.schoolyear')),
                ('term_type', models.ForeignKey(help_text='Type de période pour ce cycle (trimestre, semestre, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='school_year_cycles', to='academic.termtype')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'School Year Cycle',
                'verbose_name_plural': 'School Year Cycles',
                'db_table': 'school_year_cycle',
                'ordering': ['school_year', 'cycle'],
                'indexes': [models.Index(fields=['school_year', 'cycle'], name='syc_school_year_cycle_idx'), models.Index(fields=['school_year', 'term_type'], name='syc_school_year_term_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school_year', 'cycle'), name='unique_school_year_cycle')],
            },
        ),
    ]
