# Generated by Django 6.0.1 on 2026-01-31 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_academicyear_unique_academic_year_period_and_more'),
        ('school_operations', '0003_schoolyearcycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('level', models.ForeignKey(help_text='Niveau MASTER associé', on_delete=django.db.models.deletion.PROTECT, related_name='school_year_levels', to='academic.level')),
                ('school_year_cycle', models.ForeignKey(help_text="Cycle de l'année scolaire associé", on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='school_operations.schoolyearcycle')),
                ('track', models.ForeignKey(blank=True, help_text='Filière/option si le cycle en nécessite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_year_levels', to='academic.track')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'School Year Level',
                'verbose_name_plural': 'School Year Levels',
                'db_table': 'school_year_level',
                'ordering': ['school_year_cycle', 'level__order'],
                'indexes': [models.Index(fields=['school_year_cycle', 'level'], name='syl_syc_level_idx'), models.Index(fields=['school_year_cycle', 'track'], name='syl_syc_track_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school_year_cycle', 'level', 'track'), name='unique_school_year_level')],
            },
        ),
    ]
