# Generated by Django 6.0.1 on 2026-02-09 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_academicyear_unique_academic_year_period_and_more'),
        ('school_operations', '0004_schoolyearlevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYearLevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('coefficient', models.DecimalField(decimal_places=2, help_text='Weight/coefficient for grade calculation (must be > 0)', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year_level', models.ForeignKey(help_text='School year level for this subject assignment', on_delete=django.db.models.deletion.PROTECT, related_name='level_subjects', to='school_operations.schoolyearlevel')),
                ('subject', models.ForeignKey(help_text='Master subject reference', on_delete=django.db.models.deletion.PROTECT, related_name='year_level_assignments', to='academic.subject')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'School Year Level Subject',
                'verbose_name_plural': 'School Year Level Subjects',
                'db_table': 'school_year_level_subject',
                'ordering': ['school_year_level', 'subject'],
                'indexes': [models.Index(fields=['school_year_level', 'subject'], name='syl_subject_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school_year_level', 'subject'), name='unique_school_year_level_subject'), models.CheckConstraint(condition=models.Q(('coefficient__gt', 0)), name='school_year_level_subject_coefficient_positive')],
            },
        ),
    ]
