# Generated by Django 6.0.1 on 2026-02-11 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_academicyear_unique_academic_year_period_and_more'),
        ('school_operations', '0005_schoolyearlevelsubject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYearCycleTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('start_date', models.DateField(help_text='Start date for this period')),
                ('end_date', models.DateField(help_text='End date for this period')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year_cycle', models.ForeignKey(help_text='School year cycle for this term period', on_delete=django.db.models.deletion.PROTECT, related_name='cycle_terms', to='school_operations.schoolyearcycle')),
                ('term', models.ForeignKey(help_text='Master term reference (e.g., T1, T2, S1)', on_delete=django.db.models.deletion.PROTECT, related_name='year_cycle_assignments', to='academic.term')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'School Year Cycle Term',
                'verbose_name_plural': 'School Year Cycle Terms',
                'db_table': 'school_year_cycle_term',
                'ordering': ['school_year_cycle', 'term__order'],
                'indexes': [models.Index(fields=['school_year_cycle', 'term'], name='syc_term_idx'), models.Index(fields=['start_date', 'end_date'], name='syc_term_dates_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school_year_cycle', 'term'), name='unique_school_year_cycle_term'), models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='school_year_cycle_term_dates_valid')],
            },
        ),
        migrations.CreateModel(
            name='SchoolYearCycleTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('name', models.CharField(help_text="Display name (e.g., 'Période 1', '8h-9h')", max_length=100)),
                ('start_time', models.TimeField(help_text='Start time of the slot')),
                ('end_time', models.TimeField(help_text='End time of the slot')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Order/sequence within the day')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Status of the time slot', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year_cycle', models.ForeignKey(help_text='School year cycle for this time slot', on_delete=django.db.models.deletion.PROTECT, related_name='time_slots', to='school_operations.schoolyearcycle')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'School Year Cycle Time Slot',
                'verbose_name_plural': 'School Year Cycle Time Slots',
                'db_table': 'school_year_cycle_time_slot',
                'ordering': ['school_year_cycle', 'order', 'start_time'],
                'indexes': [models.Index(fields=['school_year_cycle', 'order'], name='syc_timeslot_order_idx'), models.Index(fields=['start_time', 'end_time'], name='syc_timeslot_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school_year_cycle', 'name'), name='unique_school_year_cycle_time_slot'), models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='school_year_cycle_time_slot_times_valid')],
            },
        ),
        migrations.CreateModel(
            name='SchoolYearTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LEFT', 'Left')], default='ACTIVE', help_text='Status of the teacher for this school year', max_length=20)),
                ('hire_date', models.DateField(blank=True, help_text='Start date of activity for this school year', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date of activity (if teacher left)', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year', models.ForeignKey(help_text='School year for this teacher assignment', on_delete=django.db.models.deletion.PROTECT, related_name='year_teachers', to='school_operations.schoolyear')),
                ('teacher', models.ForeignKey(help_text='Teacher user (must have teacher role in session)', on_delete=django.db.models.deletion.PROTECT, related_name='school_year_assignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'School Year Teacher',
                'verbose_name_plural': 'School Year Teachers',
                'db_table': 'school_year_teacher',
                'ordering': ['school_year', 'teacher'],
                'indexes': [models.Index(fields=['school_year', 'teacher'], name='sy_teacher_idx'), models.Index(fields=['status'], name='sy_teacher_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school_year', 'teacher'), name='unique_school_year_teacher')],
            },
        ),
    ]
