# Generated by Django 6.0.1 on 2026-06-14 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_superadminprofile_teacherprofile_and_more'),
        ('school_operations', '0006_schoolyearcycleterm_schoolyearcycletimeslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyearteacher',
            name='teacher',
            field=models.ForeignKey(help_text='Teacher profile (linked to a CustomUser with teacher role)', on_delete=django.db.models.deletion.PROTECT, related_name='school_year_assignments', to='account.teacherprofile'),
        ),
    ]
