# Generated by Django 6.0.1 on 2026-01-26 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('code', models.CharField(db_index=True, help_text='ISO or short code (e.g., GN)', max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='Full country name', max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('code', models.CharField(db_index=True, help_text='Short code (e.g., BOKE)', max_length=20, verbose_name='code')),
                ('name', models.CharField(help_text='Full region name', max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='geography.country', verbose_name='country')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'administrative region',
                'verbose_name_plural': 'administrative regions',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('code', models.CharField(db_index=True, help_text='Short code (e.g., KAMSAR)', max_length=20, verbose_name='code')),
                ('name', models.CharField(help_text='Full name', max_length=100, verbose_name='name')),
                ('type', models.CharField(choices=[('PREFECTURE', 'Prefecture'), ('COMMUNE', 'Commune'), ('SUBPREFECTURE', 'Subprefecture')], db_index=True, max_length=20, verbose_name='type')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent administrative unit (required for subprefectures)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='geography.administrativeunit', verbose_name='parent unit')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_units', to='geography.regionadministrative', verbose_name='region')),
            ],
            options={
                'verbose_name': 'administrative unit',
                'verbose_name_plural': 'administrative units',
                'ordering': ['region', 'type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('code', models.CharField(db_index=True, help_text='Short code (e.g., KASSAPO)', max_length=20, verbose_name='code')),
                ('name', models.CharField(help_text='Full name', max_length=100, verbose_name='name')),
                ('administrative_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='geography.administrativeunit', verbose_name='administrative unit')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'locality',
                'verbose_name_plural': 'localities',
                'ordering': ['administrative_unit', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('administrative_unit', 'code'), name='unique_locality_code_per_unit'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('administrative_unit', 'name'), name='unique_locality_name_per_unit')],
            },
        ),
        migrations.AddConstraint(
            model_name='regionadministrative',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('country', 'code'), name='unique_region_code_per_country'),
        ),
        migrations.AddConstraint(
            model_name='regionadministrative',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('country', 'name'), name='unique_region_name_per_country'),
        ),
        migrations.AddConstraint(
            model_name='administrativeunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('region', 'code'), name='unique_unit_code_per_region'),
        ),
        migrations.AddConstraint(
            model_name='administrativeunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('region', 'name'), name='unique_unit_name_per_region'),
        ),
    ]
