# Generated by Django 6.0.1 on 2026-02-09 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_remove_studentenrollment_unique_student_enrollment_per_level_and_more'),
        ('school_operations', '0004_schoolyearlevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='classroom_suffix',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', False), ('classroom_suffix__isnull', False), ('is_deleted', False)), fields=('classroom', 'first_name', 'last_name', 'classroom_suffix'), name='unique_classroom_name_suffix'),
        ),
    ]
