# Generated by Django 6.0.1 on 2026-02-11 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_studentenrollment_classroom_suffix_and_more'),
        ('school_operations', '0006_schoolyearcycleterm_schoolyearcycletimeslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('assignment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPLACED', 'Replaced'), ('ENDED', 'Ended')], default='ACTIVE', help_text='Status of the assignment', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the assignment')),
                ('end_date', models.DateField(blank=True, help_text='End date (required if REPLACED or ENDED)', null=True)),
                ('classroom', models.ForeignKey(help_text='Classroom where teaching occurs', on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='enrollment.classroom')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('replaced_by', models.ForeignKey(blank=True, help_text='Assignment that replaces this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='enrollment.teacherassignment')),
                ('school_year_level_subject', models.ForeignKey(help_text='Subject + coefficient for the level', on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='school_operations.schoolyearlevelsubject')),
                ('school_year_teacher', models.ForeignKey(help_text='Teacher assigned to school year (prerequisite)', on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='school_operations.schoolyearteacher')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'db_table': 'teacher_assignment',
                'ordering': ['classroom', 'school_year_level_subject', '-start_date'],
                'indexes': [models.Index(fields=['classroom', 'school_year_level_subject', 'assignment_status'], name='teacher_assign_class_subj_status_idx'), models.Index(fields=['school_year_teacher'], name='teacher_assign_teacher_idx'), models.Index(fields=['start_date', 'end_date'], name='teacher_assign_dates_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('assignment_status', 'ACTIVE'), ('is_deleted', False)), fields=('classroom', 'school_year_level_subject'), name='unique_active_teacher_assignment'), models.CheckConstraint(condition=models.Q(('assignment_status', 'ACTIVE'), ('end_date__isnull', False), _connector='OR'), name='teacher_assignment_end_date_required_if_not_active'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__lt', models.F('end_date')), _connector='OR'), name='teacher_assignment_dates_coherent')],
            },
        ),
    ]
