# Generated by Django 6.0.1 on 2026-02-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_teacherassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teacherassignment',
            new_name='teacher_assign_cls_subj_idx',
            old_name='teacher_assign_class_subj_status_idx',
        ),
    ]
