# Generated by Django 6.0.1 on 2026-06-14 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_superadminprofile_teacherprofile_and_more'),
        ('enrollment', '0006_rename_teacher_assign_class_subj_status_idx_teacher_assign_cls_subj_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='account.studentprofile'),
        ),
    ]
