# Generated by Django 6.0.1 on 2026-02-14 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0006_rename_teacher_assign_class_subj_status_idx_teacher_assign_cls_subj_idx'),
        ('school_operations', '0006_schoolyearcycleterm_schoolyearcycletimeslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('effective_from', models.DateField(help_text='Date when this schedule becomes effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date when this schedule ends (nullable for ongoing)', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Status of the schedule', max_length=20)),
                ('classroom', models.ForeignKey(help_text='Classroom where the session takes place', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='enrollment.classroom')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year', models.ForeignKey(help_text='School year for this schedule', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='school_operations.schoolyear')),
                ('school_year_cycle', models.ForeignKey(help_text='Cycle within the school year', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='school_operations.schoolyearcycle')),
                ('teacher_assignment', models.ForeignKey(help_text='Teacher assignment (must be ACTIVE)', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='enrollment.teacherassignment')),
                ('time_slot', models.ForeignKey(help_text='Time slot for this session', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='school_operations.schoolyearcycletimeslot')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedule',
                'ordering': ['school_year_cycle', 'classroom', 'day_of_week', 'time_slot__order'],
                'indexes': [models.Index(fields=['classroom', 'day_of_week', 'time_slot', 'status'], name='schedule_classroom_slot_idx'), models.Index(fields=['teacher_assignment', 'day_of_week', 'time_slot'], name='schedule_teacher_slot_idx'), models.Index(fields=['effective_from', 'effective_to'], name='schedule_effective_dates_idx'), models.Index(fields=['school_year_cycle', 'classroom', 'day_of_week'], name='schedule_timetable_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_from__lt', models.F('effective_to')), _connector='OR'), name='schedule_dates_coherent')],
            },
        ),
    ]
