# Generated by Django 6.0 on 2026-01-08 09:10

import django.db.models.deletion
import django.utils.timezone
import domain.accounts.models.verification
import domain.accounts.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Adresse email pour la connexion et les notifications.', max_length=254, null=True, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Numéro de téléphone au format international (+224...).', max_length=20, null=True, unique=True, validators=[domain.accounts.validators.validate_phone_number], verbose_name='Téléphone')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('email_verified', models.BooleanField(default=False, help_text="Indique si l'email a été vérifié.", verbose_name='Email vérifié')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date vérification email')),
                ('phone_verified', models.BooleanField(default=False, help_text='Indique si le téléphone a été vérifié.', verbose_name='Téléphone vérifié')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date vérification téléphone')),
                ('backup_phone', models.CharField(blank=True, help_text="Numéro d'un proche pour récupération de compte.", max_length=20, null=True, validators=[domain.accounts.validators.validate_phone_number], verbose_name='Téléphone de secours')),
                ('backup_phone_owner', models.CharField(blank=True, help_text="Nom du propriétaire (ex: 'Maman', 'Papa', 'Oncle Ibrahima').", max_length=100, null=True, verbose_name='Propriétaire du téléphone de secours')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le compte est actif.', verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, help_text="Peut accéder à l'administration Django.", verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Email ou téléphone utilisé pour la tentative.', max_length=255, verbose_name='Identifiant utilisé')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, verbose_name='Réussie')),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_credentials', 'Identifiants invalides'), ('account_disabled', 'Compte désactivé'), ('account_locked', 'Compte verrouillé'), ('not_found', 'Compte non trouvé')], max_length=30, null=True, verbose_name="Raison de l'échec")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, help_text="NULL si le compte n'existe pas.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tentative de connexion',
                'verbose_name_plural': 'Tentatives de connexion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('verified', models.BooleanField(default=False, help_text='Le numéro était-il vérifié avant retrait ?', verbose_name='Était vérifié')),
                ('added_at', models.DateTimeField(help_text='Quand le numéro a été ajouté au compte.', verbose_name="Date d'ajout")),
                ('removed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de retrait')),
                ('reason', models.CharField(choices=[('changed', 'Changé pour un nouveau'), ('lost', 'Perdu / Plus accès'), ('removed', 'Retiré volontairement'), ('replaced', "Remplacé par l'utilisateur")], default='changed', max_length=20, verbose_name='Raison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique téléphone',
                'verbose_name_plural': 'Historiques téléphones',
                'ordering': ['-removed_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='La question de sécurité.', max_length=255, verbose_name='Question')),
                ('answer_hash', models.CharField(help_text='Réponse hachée pour la sécurité.', max_length=255, verbose_name='Réponse (hachée)')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Ordre de la question (1, 2 ou 3).', verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Question de sécurité',
                'verbose_name_plural': 'Questions de sécurité',
                'ordering': ['user', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='Adresse IP')),
                ('questions_answered', models.PositiveSmallIntegerField(default=0, verbose_name='Questions répondues')),
                ('correct_answers', models.PositiveSmallIntegerField(default=0, verbose_name='Réponses correctes')),
                ('success', models.BooleanField(default=False, verbose_name='Succès')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_question_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tentative questions sécurité',
                'verbose_name_plural': 'Tentatives questions sécurité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=domain.accounts.models.verification.generate_verification_code, max_length=6, verbose_name='Code')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone')], max_length=10, verbose_name='Type')),
                ('purpose', models.CharField(choices=[('verify', 'Vérification de compte'), ('reset', 'Réinitialisation mot de passe'), ('login', 'Connexion OTP'), ('phone_change', 'Changement de téléphone'), ('email_change', 'Changement email')], max_length=20, verbose_name='But')),
                ('expires_at', models.DateTimeField(default=domain.accounts.models.verification.get_code_expiry, verbose_name='Expire le')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Tentatives')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code de vérification',
                'verbose_name_plural': 'Codes de vérification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'is_active'], name='accounts_cu_email_d617b5_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone', 'is_active'], name='accounts_cu_phone_e746af_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='accounts_cu_date_jo_fcefff_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', True), ('phone__isnull', True), _negated=True), name='user_must_have_email_or_phone', violation_error_message='Un email ou un téléphone est requis.'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['identifier', 'created_at'], name='accounts_lo_identif_19f84b_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='accounts_lo_ip_addr_71e387_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['user', 'created_at'], name='accounts_lo_user_id_b2e94d_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['success', 'created_at'], name='accounts_lo_success_c4ca36_idx'),
        ),
        migrations.AddIndex(
            model_name='phonehistory',
            index=models.Index(fields=['user', 'removed_at'], name='accounts_ph_user_id_5b5b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='phonehistory',
            index=models.Index(fields=['phone'], name='accounts_ph_phone_708923_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityquestion',
            constraint=models.UniqueConstraint(fields=('user', 'order'), name='unique_user_question_order'),
        ),
        migrations.AddConstraint(
            model_name='securityquestion',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 3)), name='valid_question_order', violation_error_message="L'ordre doit être entre 1 et 3."),
        ),
        migrations.AddIndex(
            model_name='securityquestionattempt',
            index=models.Index(fields=['user', 'created_at'], name='accounts_se_user_id_1dfcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='securityquestionattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='accounts_se_ip_addr_c54d56_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'type', 'purpose', 'is_used'], name='accounts_ve_user_id_2530c2_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['expires_at'], name='accounts_ve_expires_861e49_idx'),
        ),
    ]
