# Generated by Django 6.0 on 2026-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('security', 'Questions de sécurité')], max_length=10, verbose_name='Type'),
        ),
    ]
