# Generated by Django 6.0.1 on 2026-01-25 10:51

import django.db.models.deletion
import django.utils.timezone
import domain.account.models.verification
import domain.account.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address for login and notifications.', max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Phone number in international format (+224...).', max_length=20, null=True, unique=True, validators=[domain.account.validators.validate_phone_number], verbose_name='Phone')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email_verified', models.BooleanField(default=False, help_text='Indicates if the email has been verified.', verbose_name='Email verified')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email verification date')),
                ('phone_verified', models.BooleanField(default=False, help_text='Indicates if the phone has been verified.', verbose_name='Phone verified')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Phone verification date')),
                ('backup_phone', models.CharField(blank=True, help_text='Phone number of a relative for account recovery.', max_length=20, null=True, validators=[domain.account.validators.validate_phone_number], verbose_name='Backup phone')),
                ('backup_phone_owner', models.CharField(blank=True, help_text="Owner's name (e.g., 'Mom', 'Dad', 'Uncle John').", max_length=100, null=True, verbose_name='Backup phone owner')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the account is active.', verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Can access Django admin.', verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last login')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Email or phone used for the attempt.', max_length=255, verbose_name='Identifier used')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, verbose_name='Successful')),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_credentials', 'Invalid credentials'), ('account_disabled', 'Account disabled'), ('account_locked', 'Account locked'), ('not_found', 'Account not found')], max_length=30, null=True, verbose_name='Failure reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, help_text="NULL if account doesn't exist.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login attempt',
                'verbose_name_plural': 'Login attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('verified', models.BooleanField(default=False, help_text='Was the number verified before removal?', verbose_name='Was verified')),
                ('added_at', models.DateTimeField(help_text='When the number was added to the account.', verbose_name='Added at')),
                ('removed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Removed at')),
                ('reason', models.CharField(choices=[('changed', 'Changed to a new one'), ('lost', 'Lost / No longer accessible'), ('removed', 'Voluntarily removed'), ('replaced', 'Replaced by user')], default='changed', max_length=20, verbose_name='Reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Phone history',
                'verbose_name_plural': 'Phone histories',
                'ordering': ['-removed_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='The security question.', max_length=255, verbose_name='Question')),
                ('answer_hash', models.CharField(help_text='Hashed answer for security.', max_length=255, verbose_name='Answer (hashed)')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Question order (1, 2, or 3).', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Security question',
                'verbose_name_plural': 'Security questions',
                'ordering': ['user', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP address')),
                ('questions_answered', models.PositiveSmallIntegerField(default=0, verbose_name='Questions answered')),
                ('correct_answers', models.PositiveSmallIntegerField(default=0, verbose_name='Correct answers')),
                ('success', models.BooleanField(default=False, verbose_name='Success')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_question_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Security question attempt',
                'verbose_name_plural': 'Security question attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, default=domain.account.models.verification.generate_verification_code, max_length=6, verbose_name='Code')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('security', 'Security Questions')], max_length=10, verbose_name='Type')),
                ('purpose', models.CharField(choices=[('verify', 'Account Verification'), ('reset', 'Password Reset'), ('login', 'OTP Login'), ('phone_change', 'Phone Change'), ('email_change', 'Email Change')], max_length=20, verbose_name='Purpose')),
                ('expires_at', models.DateTimeField(default=domain.account.models.verification.get_code_expiry, verbose_name='Expires at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Attempts')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Verification code',
                'verbose_name_plural': 'Verification codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'is_active'], name='account_cus_email_36ea05_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone', 'is_active'], name='account_cus_phone_a20e54_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='account_cus_date_jo_bc4988_idx'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', True), ('phone__isnull', True), _negated=True), name='user_must_have_email_or_phone', violation_error_message='An email or phone is required.'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['identifier', 'created_at'], name='account_log_identif_ff1fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='account_log_ip_addr_0da8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['user', 'created_at'], name='account_log_user_id_d98743_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['success', 'created_at'], name='account_log_success_09945a_idx'),
        ),
        migrations.AddIndex(
            model_name='phonehistory',
            index=models.Index(fields=['user', 'removed_at'], name='account_pho_user_id_0bd85d_idx'),
        ),
        migrations.AddIndex(
            model_name='phonehistory',
            index=models.Index(fields=['phone'], name='account_pho_phone_36b4e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityquestion',
            constraint=models.UniqueConstraint(fields=('user', 'order'), name='unique_user_question_order'),
        ),
        migrations.AddConstraint(
            model_name='securityquestion',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 3)), name='valid_question_order', violation_error_message='Order must be between 1 and 3.'),
        ),
        migrations.AddIndex(
            model_name='securityquestionattempt',
            index=models.Index(fields=['user', 'created_at'], name='account_sec_user_id_f52bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='securityquestionattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='account_sec_ip_addr_349b73_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'type', 'purpose', 'is_used'], name='account_ver_user_id_575a52_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['expires_at'], name='account_ver_expires_8aa5be_idx'),
        ),
    ]
