# Generated by Django 6.0.1 on 2026-02-13 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('relationship_type', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('GUARDIAN', 'Legal Guardian'), ('OTHER', 'Other')], default='GUARDIAN', help_text='Type of relationship', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary contact for the child')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the relationship', null=True)),
                ('child', models.ForeignKey(help_text='Child (student) user account', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('parent', models.ForeignKey(help_text='Parent user account', on_delete=django.db.models.deletion.CASCADE, related_name='children_relationships', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Parent-Child Relationship',
                'verbose_name_plural': 'Parent-Child Relationships',
                'db_table': 'parent_child',
                'ordering': ['child', 'parent'],
                'indexes': [models.Index(fields=['parent'], name='parent_child_parent_idx'), models.Index(fields=['child'], name='parent_child_child_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('parent', 'child'), name='unique_parent_child_relationship')],
            },
        ),
    ]
