# Generated by Django 6.0.1 on 2026-06-14 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_parentchild'),
        ('geography', '0001_initial'),
        ('school_operations', '0006_schoolyearcycleterm_schoolyearcycletimeslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('department', models.CharField(blank=True, help_text='Service / département (ex : DGESS, Inspection régionale).', max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profiles/super_admins/')),
            ],
            options={
                'verbose_name': 'Profil super-administrateur',
                'verbose_name_plural': 'Profils super-administrateurs',
                'db_table': 'super_admin_profile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date de naissance.', null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe.', max_length=1)),
                ('employee_id', models.CharField(blank=True, help_text='Matricule fonctionnaire (MEN) si applicable.', max_length=50, null=True)),
                ('diploma', models.CharField(choices=[('bepc', 'BEPC'), ('bac', 'Baccalauréat'), ('bts', 'BTS'), ('dut', 'DUT'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], help_text='Niveau de diplôme le plus élevé.', max_length=20)),
                ('employment_type', models.CharField(choices=[('fonctionnaire', 'Fonctionnaire'), ('contractuel', 'Contractuel'), ('vacataire', 'Vacataire'), ('benevole', 'Bénévole')], default='contractuel', help_text="Statut d'emploi (fonctionnaire, contractuel, vacataire...).", max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profiles/teachers/')),
                ('address', models.TextField(blank=True, help_text='Adresse de résidence.')),
            ],
            options={
                'verbose_name': 'Profil enseignant',
                'verbose_name_plural': 'Profils enseignants',
                'db_table': 'teacher_profile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='parentchild',
            options={'ordering': ['child', 'parent'], 'verbose_name': 'Relation parent-enfant', 'verbose_name_plural': 'Relations parent-enfant'},
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Contact principal pour cet enfant.'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes complémentaires sur la relation.', null=True),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='relationship_type',
            field=models.CharField(choices=[('FATHER', 'Père'), ('MOTHER', 'Mère'), ('GUARDIAN', 'Tuteur légal'), ('OTHER', 'Autre')], default='GUARDIAN', help_text='Type de relation.', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('position', models.CharField(help_text="Fonction au sein de l'équipe (ex : Support, Data Manager).", max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profiles/admins/')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil administrateur',
                'verbose_name_plural': 'Profils administrateurs',
                'db_table': 'admin_profile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe.', max_length=1)),
                ('occupation', models.CharField(blank=True, help_text='Profession (commerçant, fonctionnaire, agriculteur...).', max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profiles/parents/')),
                ('address', models.TextField(blank=True, help_text='Adresse de résidence.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('locality', models.ForeignKey(blank=True, help_text='Localité de résidence.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parents_residing_here', to='geography.locality')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil parent',
                'verbose_name_plural': 'Profils parents',
                'db_table': 'parent_profile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='parent',
            field=models.ForeignKey(help_text='Profil parent.', on_delete=django.db.models.deletion.CASCADE, related_name='children_relationships', to='account.parentprofile'),
        ),
        migrations.CreateModel(
            name='SchoolAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('photo', models.FileField(blank=True, null=True, upload_to='profiles/school_admins/')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil admin école',
                'verbose_name_plural': 'Profils admin école',
                'db_table': 'school_admin_profile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolAdminAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('position', models.CharField(choices=[('director', 'Directeur'), ('deputy_director', 'Directeur adjoint'), ('censor', 'Censeur'), ('general_secretary', 'Secrétaire général'), ('registrar', 'Surveillant général'), ('bursar', 'Économe'), ('other', 'Autre')], help_text='Poste occupé dans cette école.', max_length=30)),
                ('start_date', models.DateField(help_text="Date de début d'affectation.")),
                ('end_date', models.DateField(blank=True, help_text='Date de fin (vide = affectation en cours).', null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Affectation principale (utilisée par défaut pour ce school admin).')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school', models.ForeignKey(help_text='École de rattachement.', on_delete=django.db.models.deletion.PROTECT, related_name='admin_assignments', to='school_operations.school')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('school_admin', models.ForeignKey(help_text="Profil de l'administrateur école.", on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='account.schooladminprofile')),
            ],
            options={
                'verbose_name': 'Affectation admin école',
                'verbose_name_plural': 'Affectations admin école',
                'db_table': 'school_admin_assignment',
                'ordering': ['-start_date', 'school__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('date_of_birth', models.DateField(help_text='Date de naissance.')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe (M/F).', max_length=1)),
                ('birth_cert_number', models.CharField(blank=True, help_text="Numéro d'acte de naissance.", max_length=50, null=True)),
                ('nationality', models.CharField(default='GN', help_text='Code pays ISO (GN, ML, SN, CI...).', max_length=3)),
                ('photo', models.FileField(blank=True, help_text="Photo d'identité.", null=True, upload_to='profiles/students/')),
                ('address', models.TextField(blank=True, help_text='Adresse de résidence.')),
                ('has_disability', models.BooleanField(default=False, help_text="L'élève présente-t-il un handicap nécessitant un suivi ?")),
                ('disability_notes', models.TextField(blank=True, help_text='Précisions sur le handicap (vide si has_disability=False).')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('place_of_birth', models.ForeignKey(blank=True, help_text='Localité de naissance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_born_here', to='geography.locality')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('user', models.OneToOneField(help_text='Compte utilisateur lié (obligatoire).', on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil élève',
                'verbose_name_plural': 'Profils élèves',
                'db_table': 'student_profile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='child',
            field=models.ForeignKey(help_text='Profil élève.', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='account.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='parentchild',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_primary', True)), fields=('child',), name='unique_primary_parent_per_child'),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='superadminprofile',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='super_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='schooladminassignment',
            index=models.Index(fields=['school_admin', 'school'], name='sa_assign_admin_school_idx'),
        ),
        migrations.AddIndex(
            model_name='schooladminassignment',
            index=models.Index(fields=['school', 'end_date'], name='sa_assign_school_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='schooladminassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_deleted', False)), fields=('school_admin', 'school'), name='unique_active_school_admin_assignment'),
        ),
        migrations.AddConstraint(
            model_name='schooladminassignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__lt', models.F('end_date')), _connector='OR'), name='school_admin_assignment_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='schooladminassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_deleted', False), ('is_primary', True)), fields=('school_admin',), name='unique_primary_school_admin_assignment'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['birth_cert_number'], name='student_profile_birth_cert_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('birth_cert_number__isnull', False), ('is_deleted', False)), fields=('birth_cert_number',), name='unique_student_birth_cert_number'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['employee_id'], name='teacher_profile_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['diploma'], name='teacher_profile_diploma_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id__isnull', False), ('is_deleted', False)), fields=('employee_id',), name='unique_teacher_employee_id'),
        ),
    ]
