# Generated by Django 6.0.1 on 2026-06-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_superadminprofile_teacherprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/admins/'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/parents/'),
        ),
        migrations.AlterField(
            model_name='schooladminprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/school_admins/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo d'identité.", null=True, upload_to='profiles/students/'),
        ),
        migrations.AlterField(
            model_name='superadminprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/super_admins/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/teachers/'),
        ),
    ]
