# Generated by Django 6.0.1 on 2026-06-15 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_adminprofile_photo_alter_parentprofile_photo_and_more'),
        ('geography', '0001_initial'),
        ('school_operations', '0007_alter_schoolyearteacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/admins/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='position',
            field=models.CharField(help_text="Fonction au sein de l'équipe (ex : Support, Data Manager).", max_length=100, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='child',
            field=models.ForeignKey(help_text='Profil élève.', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='account.studentprofile', verbose_name='Enfant'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Contact principal pour cet enfant.', verbose_name='Contact principal'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes complémentaires sur la relation.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='parent',
            field=models.ForeignKey(help_text='Profil parent.', on_delete=django.db.models.deletion.CASCADE, related_name='children_relationships', to='account.parentprofile', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='parentchild',
            name='relationship_type',
            field=models.CharField(choices=[('FATHER', 'Père'), ('MOTHER', 'Mère'), ('GUARDIAN', 'Tuteur légal'), ('OTHER', 'Autre')], default='GUARDIAN', help_text='Type de relation.', max_length=20, verbose_name='Type de relation'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse de résidence.', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe.', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='locality',
            field=models.ForeignKey(blank=True, help_text='Localité de résidence.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parents_residing_here', to='geography.locality', verbose_name='Localité'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='occupation',
            field=models.CharField(blank=True, help_text='Profession (commerçant, fonctionnaire, agriculteur...).', max_length=100, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/parents/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='schooladminassignment',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date de fin (vide = affectation en cours).', null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='schooladminassignment',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Affectation principale (utilisée par défaut pour ce school admin).', verbose_name='Affectation principale'),
        ),
        migrations.AlterField(
            model_name='schooladminassignment',
            name='position',
            field=models.CharField(choices=[('director', 'Directeur'), ('deputy_director', 'Directeur adjoint'), ('censor', 'Censeur'), ('general_secretary', 'Secrétaire général'), ('registrar', 'Surveillant général'), ('bursar', 'Économe'), ('other', 'Autre')], help_text='Poste occupé dans cette école.', max_length=30, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='schooladminassignment',
            name='school',
            field=models.ForeignKey(help_text='École de rattachement.', on_delete=django.db.models.deletion.PROTECT, related_name='admin_assignments', to='school_operations.school', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='schooladminassignment',
            name='school_admin',
            field=models.ForeignKey(help_text="Profil de l'administrateur école.", on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='account.schooladminprofile', verbose_name='Administrateur école'),
        ),
        migrations.AlterField(
            model_name='schooladminassignment',
            name='start_date',
            field=models.DateField(help_text="Date de début d'affectation.", verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='schooladminprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/school_admins/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='schooladminprofile',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse de résidence.', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='birth_cert_number',
            field=models.CharField(blank=True, help_text="Numéro d'acte de naissance.", max_length=50, null=True, verbose_name="Numéro d'acte de naissance"),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(help_text='Date de naissance.', verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='disability_notes',
            field=models.TextField(blank=True, help_text='Précisions sur le handicap (vide si has_disability=False).', verbose_name='Précisions sur le handicap'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe (M/F).', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='has_disability',
            field=models.BooleanField(default=False, help_text="L'élève présente-t-il un handicap nécessitant un suivi ?", verbose_name='Situation de handicap'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(default='GN', help_text='Code pays ISO (GN, ML, SN, CI...).', max_length=3, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo d'identité.", null=True, upload_to='profiles/students/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, help_text='Localité de naissance.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_born_here', to='geography.locality', verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié (obligatoire).', on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='superadminprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Service / département (ex : DGESS, Inspection régionale).', max_length=100, verbose_name='Service / Département'),
        ),
        migrations.AlterField(
            model_name='superadminprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/super_admins/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='superadminprofile',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='super_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse de résidence.', verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date de naissance.', null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='diploma',
            field=models.CharField(choices=[('bepc', 'BEPC'), ('bac', 'Baccalauréat'), ('bts', 'BTS'), ('dut', 'DUT'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], help_text='Niveau de diplôme le plus élevé.', max_length=20, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Matricule fonctionnaire (MEN) si applicable.', max_length=50, null=True, verbose_name='Matricule fonctionnaire'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employment_type',
            field=models.CharField(choices=[('fonctionnaire', 'Fonctionnaire'), ('contractuel', 'Contractuel'), ('vacataire', 'Vacataire'), ('benevole', 'Bénévole')], default='contractuel', help_text="Statut d'emploi (fonctionnaire, contractuel, vacataire...).", max_length=20, verbose_name="Statut d'emploi"),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], help_text='Sexe.', max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/teachers/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(help_text='Compte utilisateur lié.', on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur'),
        ),
    ]
