# Generated by Django 6.0.1 on 2026-02-11 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_remove_academicyear_unique_academic_year_period_and_more'),
        ('enrollment', '0006_rename_teacher_assign_class_subj_status_idx_teacher_assign_cls_subj_idx'),
        ('school_operations', '0006_schoolyearcycleterm_schoolyearcycletimeslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('name', models.CharField(help_text="Name of the assessment (e.g., 'Trimester 1 Exams')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the assessment')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Status of the assessment', max_length=20)),
                ('start_date', models.DateField(help_text='Start date for the assessment period')),
                ('end_date', models.DateField(help_text='End date for the assessment period')),
                ('assessment_type', models.ForeignKey(help_text='Type of assessment (exam, test, project, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academic.assessmenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year', models.ForeignKey(help_text='School year for this assessment', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='school_operations.schoolyear')),
                ('school_year_cycle', models.ForeignKey(help_text='Specific cycle for this assessment', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='school_operations.schoolyearcycle')),
                ('school_year_cycle_term', models.ForeignKey(help_text='Specific term period for this assessment', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='school_operations.schoolyearcycleterm')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessment',
                'ordering': ['-start_date', 'assessment_type'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Status of the assessment subject', max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Maximum possible score for this exam', max_digits=6)),
                ('instructions', models.TextField(blank=True, help_text='Instructions or notes for this specific exam')),
                ('assessment', models.ForeignKey(help_text='Parent assessment framework', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_subjects', to='assessment.assessment')),
                ('classroom', models.ForeignKey(help_text='Classroom taking this exam', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_subjects', to='enrollment.classroom')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year_level_subject', models.ForeignKey(help_text='Subject + coefficient for the level', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_subjects', to='school_operations.schoolyearlevelsubject')),
                ('teacher_assignment', models.ForeignKey(help_text='Teacher responsible for this exam (frozen at creation)', on_delete=django.db.models.deletion.PROTECT, related_name='assessment_subjects', to='enrollment.teacherassignment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Assessment Subject',
                'verbose_name_plural': 'Assessment Subjects',
                'db_table': 'assessment_subject',
                'ordering': ['assessment', 'classroom', 'school_year_level_subject'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score obtained by the student (NULL if absent)', max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False, help_text='Student was absent for this assessment')),
                ('is_excused', models.BooleanField(default=False, help_text='Absence was excused')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VALIDATED', 'Validated'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Status of this grade', max_length=20)),
                ('remark', models.CharField(blank=True, help_text='Optional teacher comment/remark', max_length=500)),
                ('assessment_subject', models.ForeignKey(help_text='The exam this grade belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='assessment.assessmentsubject')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('student_enrollment', models.ForeignKey(help_text='Student enrollment (must be in same classroom)', on_delete=django.db.models.deletion.PROTECT, related_name='student_assessments', to='enrollment.studentenrollment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Student Assessment',
                'verbose_name_plural': 'Student Assessments',
                'db_table': 'student_assessment',
                'ordering': ['assessment_subject', 'student_enrollment'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school_year_cycle', 'assessment_type'], name='assess_cycle_type_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status'], name='assess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['start_date', 'end_date'], name='assess_dates_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school_year_cycle', 'assessment_type', 'school_year_cycle_term'), name='unique_assessment_per_type_period_cycle'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='assessment_dates_coherent'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubject',
            index=models.Index(fields=['assessment', 'classroom', 'school_year_level_subject'], name='assess_subj_assess_cls_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubject',
            index=models.Index(fields=['teacher_assignment'], name='assess_subj_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubject',
            index=models.Index(fields=['status'], name='assess_subj_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment', 'classroom', 'school_year_level_subject'), name='unique_assessment_subject_per_assessment_classroom_subject'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsubject',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='assessment_subject_max_score_positive'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(fields=['assessment_subject', 'student_enrollment'], name='stud_assess_subj_enroll_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(fields=['status'], name='stud_assess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studentassessment',
            index=models.Index(fields=['is_absent', 'is_excused'], name='stud_assess_absence_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('assessment_subject', 'student_enrollment'), name='unique_student_assessment_per_subject_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='studentassessment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_absent', True), ('raw_score__isnull', True)), models.Q(('is_absent', False), ('raw_score__gte', 0)), _connector='OR'), name='student_assessment_score_bounds'),
        ),
    ]
