# Generated by Django 6.0.1 on 2026-02-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assessmentsubject',
            new_name='ass_subj_acls_subj_idx',
            old_name='assess_subj_assess_cls_subj_idx',
        ),
    ]
