# Generated by Django 6.0.1 on 2026-02-12 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_rename_assess_subj_assess_cls_subj_idx_ass_subj_acls_subj_idx'),
        ('enrollment', '0006_rename_teacher_assign_class_subj_status_idx_teacher_assign_cls_subj_idx'),
        ('school_operations', '0006_schoolyearcycleterm_schoolyearcycletimeslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted overall average for this term', max_digits=6, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Class rank for this term (per classroom)', null=True)),
                ('decision', models.CharField(blank=True, help_text='Manual decision (optional)', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when report card was generated')),
                ('is_final', models.BooleanField(default=False, help_text='Frozen report card; cannot be modified when True')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of computed data for audit and export')),
                ('classroom', models.ForeignKey(help_text='Classroom where the student is enrolled', on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='enrollment.classroom')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year_cycle_term', models.ForeignKey(help_text='Term for this report card', on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='school_operations.schoolyearcycleterm')),
                ('student_enrollment', models.ForeignKey(help_text='Student enrollment for this report card', on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='enrollment.studentenrollment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'db_table': 'report_card',
                'ordering': ['school_year_cycle_term', 'classroom', 'student_enrollment'],
            },
        ),
        migrations.CreateModel(
            name='ReportCardSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('average', models.DecimalField(blank=True, decimal_places=2, help_text='Average score for this subject', max_digits=6, null=True)),
                ('coefficient', models.DecimalField(decimal_places=2, help_text='Coefficient used for weighting', max_digits=5)),
                ('teacher_name', models.CharField(blank=True, help_text='Optional teacher name snapshot', max_length=255)),
                ('remark', models.CharField(blank=True, help_text='Optional subject remark', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('report_card', models.ForeignKey(help_text='Parent report card', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='assessment.reportcard')),
                ('school_year_level_subject', models.ForeignKey(help_text='Subject + coefficient', on_delete=django.db.models.deletion.PROTECT, related_name='report_card_subjects', to='school_operations.schoolyearlevelsubject')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Report Card Subject',
                'verbose_name_plural': 'Report Card Subjects',
                'db_table': 'report_card_subject',
                'ordering': ['report_card', 'school_year_level_subject'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, help_text='Annual weighted average', max_digits=6, null=True)),
                ('decision', models.CharField(blank=True, help_text='Manual decision (PASS/FAIL/REPEAT, etc.)', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when transcript was generated')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of aggregated data for audit/export')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year', models.ForeignKey(help_text='School year', on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='school_operations.schoolyear')),
                ('student_enrollment', models.ForeignKey(help_text='Student enrollment', on_delete=django.db.models.deletion.PROTECT, related_name='transcripts', to='enrollment.studentenrollment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Transcript',
                'verbose_name_plural': 'Transcripts',
                'db_table': 'transcript',
                'ordering': ['school_year', 'student_enrollment'],
            },
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['school_year_cycle_term', 'classroom'], name='report_card_term_class_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student_enrollment'], name='report_card_student_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student_enrollment', 'school_year_cycle_term'), name='unique_report_card_per_student_term'),
        ),
        migrations.AddConstraint(
            model_name='reportcardsubject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('report_card', 'school_year_level_subject'), name='unique_report_card_subject'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student_enrollment', 'school_year'), name='unique_transcript_per_student_year'),
        ),
    ]
