"""Serializer for AcademicYear model."""
from rest_framework import serializers

from domain.academic.models import AcademicYear


class AcademicYearSerializer(serializers.ModelSerializer):
    """Serializer for AcademicYear model."""

    class Meta:
        model = AcademicYear
        fields = [
            "id",
            "code",
            "start_year",
            "end_year",
            "is_current",
            "status",
            "created_at",
            "updated_at",
        ]
        read_only_fields = ["id", "code", "created_at", "updated_at"]

    def validate(self, attrs):
        """Validate the data."""
        start_year = attrs.get("start_year")
        end_year = attrs.get("end_year")

        if start_year and end_year:
            if end_year != start_year + 1:
                raise serializers.ValidationError(
                    {"end_year": "End year must be start_year + 1"}
                )

        return attrs

    def create(self, validated_data):
        """Create a new academic year."""
        # Code is auto-generated by signal
        validated_data["code"] = (
            f"{validated_data['start_year']}-{validated_data['end_year']}"
        )
        return super().create(validated_data)
