# Generated by Django 6.0.1 on 2026-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='code',
            field=models.CharField(blank=True, help_text='Code court (ex. 2024-2025) - Auto-generated if not provided', max_length=20, unique=True),
        ),
    ]
