# Generated by Django 6.0.1 on 2026-01-30 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_academicyear_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicyear',
            name='unique_academic_year_period',
        ),
        migrations.RemoveConstraint(
            model_name='level',
            name='unique_level_code_per_cycle',
        ),
        migrations.RemoveConstraint(
            model_name='level',
            name='unique_level_name_per_cycle',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='unique_term_code_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='term',
            name='unique_term_order_per_type',
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_track_code_per_cycle',
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_track_name_per_cycle',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='termtype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', help_text="Statut de l'année académique", max_length=20),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='code',
            field=models.CharField(db_index=True, help_text='Code court (ex. COMPO, COURS, PART)', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='name',
            field=models.CharField(db_index=True, help_text='Nom lisible (ex. Composition, Note de cours)', max_length=100),
        ),
        migrations.AlterField(
            model_name='assessmenttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='code',
            field=models.CharField(db_index=True, help_text='Code court (ex. MAT, PRI, COL, LYC)', max_length=10),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name',
            field=models.CharField(db_index=True, help_text='Nom lisible (ex. Maternelle, Primaire)', max_length=100),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='level',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='level',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='level',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='level',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='level',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(db_index=True, help_text='Code court (ex. MATH, PHYS, FRAN)', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, help_text='Nom lisible (ex. Mathématiques, Physique)', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='term',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='term',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='term',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='term',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='term',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='termtype',
            name='code',
            field=models.CharField(db_index=True, help_text='Code court (ex. TRIMESTER, SEMESTER)', max_length=20),
        ),
        migrations.AlterField(
            model_name='termtype',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='termtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='termtype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='termtype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='termtype',
            name='name',
            field=models.CharField(db_index=True, help_text='Nom lisible (ex. Trimestre, Semestre)', max_length=100),
        ),
        migrations.AlterField(
            model_name='termtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='track',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at'),
        ),
        migrations.AlterField(
            model_name='track',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='track',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted'),
        ),
        migrations.AlterField(
            model_name='track',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_current'], name='academic_year_is_current_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['status'], name='academic_year_status_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['start_year'], name='academic_year_start_year_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['start_year', 'end_year'], name='academic_year_period_idx'),
        ),
        migrations.AddIndex(
            model_name='cycle',
            index=models.Index(fields=['has_track', 'code'], name='cycle_has_track_code_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['cycle', 'order'], name='level_cycle_order_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['cycle', 'track'], name='level_cycle_track_idx'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['cycle', 'code'], name='level_cycle_code_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['term_type', 'order'], name='term_type_order_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['term_type', 'code'], name='term_type_code_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['cycle', 'code'], name='track_cycle_code_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['cycle', 'name'], name='track_cycle_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('start_year', 'end_year'), name='unique_academic_year_period'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_academic_year_code'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_assessment_type_code'),
        ),
        migrations.AddConstraint(
            model_name='assessmenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_assessment_type_name'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_cycle_code'),
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_cycle_name'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cycle', 'code'), name='unique_level_code_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cycle', 'name'), name='unique_level_name_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_subject_code'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_subject_name'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('term_type', 'code'), name='unique_term_code_per_type'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('term_type', 'order'), name='unique_term_order_per_type'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.CheckConstraint(condition=models.Q(('order__gt', 0)), name='term_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='termtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_term_type_code'),
        ),
        migrations.AddConstraint(
            model_name='termtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_term_type_name'),
        ),
        migrations.AddConstraint(
            model_name='termtype',
            constraint=models.CheckConstraint(condition=models.Q(('period_count__gt', 0)), name='term_type_period_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cycle', 'code'), name='unique_track_code_per_cycle'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cycle', 'name'), name='unique_track_name_per_cycle'),
        ),
    ]
