# Generated by Django 6.0.1 on 2026-06-15 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0007_alter_studentenrollment_student'),
        ('school_operations', '0007_alter_schoolyearteacher_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('document_type', models.CharField(choices=[('bulletin', 'Bulletin de notes'), ('transcript', 'Relevé de notes annuel'), ('attestation', 'Attestation de scolarité'), ('certificat', 'Certificat de scolarité'), ('carte', 'Carte scolaire')], db_index=True, max_length=20, verbose_name='Type de document')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('generating', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='generated_documents/', verbose_name='Fichier généré')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Généré le')),
                ('file_hash', models.CharField(blank=True, help_text='Permet de détecter les générations identiques.', max_length=64, verbose_name='Empreinte SHA-256')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (octets)')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_year_cycle_term', models.ForeignKey(blank=True, help_text='Période concernée (obligatoire pour bulletin/relevé).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to='school_operations.schoolyearcycleterm', verbose_name='Période')),
                ('student_enrollment', models.ForeignKey(help_text='Inscription pour laquelle le document est généré.', on_delete=django.db.models.deletion.PROTECT, related_name='document_requests', to='enrollment.studentenrollment', verbose_name='Inscription élève')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Demande de document',
                'verbose_name_plural': 'Demandes de documents',
                'db_table': 'document_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_enrollment', 'document_type', 'school_year_cycle_term'], name='doc_req_lookup_idx'), models.Index(fields=['status'], name='doc_req_status_idx'), models.Index(fields=['file_hash'], name='doc_req_hash_idx')],
            },
        ),
    ]
