# Generated by Django 6.0.1 on 2026-06-03 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0006_rename_teacher_assign_class_subj_status_idx_teacher_assign_cls_subj_idx'),
        ('school_operations', '0006_schoolyearcycleterm_schoolyearcycletimeslot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('REGISTRATION', 'Inscription'), ('TUITION', 'Scolarité'), ('MATERIAL', 'Fournitures'), ('EXAM', 'Examen'), ('TRANSPORT', 'Transport'), ('MEAL', 'Cantine'), ('PTA', 'APE'), ('OTHER', 'Autre')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('ANNUAL', 'Annuel'), ('TERM', 'Trimestriel'), ('MONTHLY', 'Mensuel')], max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
                'db_table': 'fee_type',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_fees', to='finance.feetype')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='school_operations.schoolyear')),
                ('school_year_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='school_operations.schoolyearcycle')),
                ('school_year_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='school_operations.schoolyearlevel')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'School Fee',
                'verbose_name_plural': 'School Fees',
                'db_table': 'school_fee',
                'ordering': ['school_year', 'school_year_level', 'fee_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Monnaie mobile'), ('CHECK', 'Chèque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('collected_by', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('school_fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.schoolfee')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='enrollment.studentenrollment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Student Payment',
                'verbose_name_plural': 'Student Payments',
                'db_table': 'student_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolfee',
            index=models.Index(fields=['school_year', 'school_year_level'], name='school_fee_year_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolfee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school_year', 'school_year_level', 'fee_type', 'school_year_cycle'), name='unique_school_fee_assignment'),
        ),
        migrations.AddConstraint(
            model_name='schoolfee',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='school_fee_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['student_enrollment'], name='payment_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['school_fee'], name='payment_fee_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['payment_date'], name='payment_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gt', 0)), name='payment_amount_positive'),
        ),
    ]
